### ISSUE TITLE
Please push tag for version used to release 2.0.0-RC2

### ISSUE THREAD

**Issue by pzygielo** [eclipse-ee4j/jca-api#105]
https://repo.maven.apache.org/maven2/jakarta/resource/jakarta.resource-api/2.0.0-RC2

Additionally - there is tag [2.0.0](https://github.com/eclipse-ee4j/jca-api/releases/tag/2.0.0) for not published version, which will probably make conflict on true 2.0.0 release. Consider deletion of it, please.

**Comment by pzygielo** [comment]
It seems that previous job [jca-api-release/30](https://ci.eclipse.org/jca/job/jca-api-release/30/console) pushed new release branch and tag back to github, while the next [jca-api-release/31](https://ci.eclipse.org/jca/job/jca-api-release/31/console) and the next [jca-api-release/32](https://ci.eclipse.org/jca/job/jca-api-release/32/console) didn't.
:disappointed:

**Comment by smillidge** [comment]
OK I will take a look and fix the Jenkins jobs
