### ISSUE TITLE
Compatibility certification request for Eclipse GlassFish as implementation of Jakarta Connectors 2.0

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/jca-api#114]
# 2.0 Certification Request

- [x] Organization Name ("Organization") and, if applicable, URL: <br/>
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable): <br/>
  [GlassFish 6.0.0-M1](https://www.eclipse.org/downloads/download.php?file=/ee4j/glassfish/glassfish-6.0.0-M1.zip)
- [x] Specification Name, Version and download URL: <br/>
  [Jakarta Connectors 2.0](https://jakarta.ee/specifications/connectors/2.0/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL: <br/>
  [Jakarta Connectors TCK 2.0.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee9-eftl/staged-900/jakarta-connectors-tck-2.0.0.zip), SHA-256: d5dcaaeb486a0ab86b99f0f421244388cdbd3f342141d15fc25a2734ac7d03c3     
- [x] Public URL of TCK Results Summary: <br/>
  [TCK results summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-connectors/2.0/TCK-Results)
- [x] Any Additional Specification Certification Requirements: <br/>
  None
- [x] Java runtime used to run the implementation: <br/>
  java version "1.8.0_202"
  Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
  Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)
- [x] Summary of the information for the certification environment, operating system, cloud, ...: <br/>
  Linux basic-t3vt7 3.10.0-1062.el7.x86_64 #1 SMP Thu Jul 18 20:25:13 UTC 2019 x86_64 GNU/Linux
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by smillidge** [comment]
@njr-11 can you approve this one. It will look weird approving it myself :-)

**Comment by njr-11** [comment]
@smillidge I approved another PR which I recently received a notification about, but with regard to this issue I don't see anywhere to add an approval.  Is there a process to follow for signing off on/approving for this?

**Comment by edbratt** [comment]
This is long past lazy consensus time-period. I will mark it approved and close.
