### ISSUE TITLE
Compatibility Certification Request for Eclipse GlassFish 7.0.0-M4

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/jca-api#132]
# 2.1 Certification Request

- [x] Organization Name ("Organization") and, if applicable, URL: <br/>
  Eclipse Foundation
- [x] Product Name, Version and download URL (if applicable): <br/>
  [GlassFish 7.0.0-M4](https://repo1.maven.org/maven2/org/glassfish/main/distributions/glassfish/7.0.0-M4/glassfish-7.0.0-M4.zip)
- [x] Specification Name, Version and download URL: <br/>
  [Jakarta Connectors 2.1](https://jakarta.ee/specifications/connectors/2.1/)
- [x] TCK Version, digital SHA-256 fingerprint and download URL: 
  [Jakarta Connectors TCK 2.1.0](https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-connectors-tck-2.1.0.zip), SHA-256: 9af19fb2401b6faee29640d2063db85ec85e97283934b5bcb77c89fa3ca53958     
- [x] Public URL of TCK Results Summary: 
  [TCK results summary](https://eclipse-ee4j.github.io/glassfish/certifications/jakarta-connectors/2.1/TCK-Results)
- [x] Any Additional Specification Certification Requirements: 
  None
- [x] Java runtime used to run the implementation: 
`openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)`
- [x] Summary of the information for the certification environment, operating system, cloud, ...: 
`Linux basic-z8drp 5.14.14-200.fc34.x86_64 #1 SMP Wed Oct 20 16:15:12 UTC 2021 x86_64 GNU/Linux`
- [x] By checking this box I acknowledge that the Organization I represent accepts the terms of the [EFTL](https://www.eclipse.org/legal/tck.php).
- [x] By checking this box I attest that all TCK requirements have been met, including any compatibility rules.

**Comment by ivargrimstad** [comment]
SHA: f8c018fe56f19899a780df3f8d10c93555996861038b7da03eee5421574d4b9b

**Comment by ivargrimstad** [comment]
There is a new version of the TCK, so the SHA has changed again: https://download.eclipse.org/ee4j/jakartaee-tck/jakartaee10/staged/eftl/jakarta-connectors-tck-2.1.0-tckinfo.txt

**Comment by ivargrimstad** [comment]
LGTM +1

**Comment by smillidge** [comment]
Approved
