### ISSUE TITLE
Release to OSSRH staging repository

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jca-api#15]
- [x] Uptake new Eclipse versions of dependencies (if any). Use [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) wiki to find components versions to use.

- [x] Release to OSSRH staging repository

- [x] Update [GlassFish 5.1 Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) with released version number.

**Comment by m0mus** [comment]
@alexsm82 [GF Release Tracker](https://wiki.eclipse.org/Eclipse_GlassFish_5.1_Components_Release_Tracker) says that JCA API 1.7.2 is released to staging, but I don't see it here: https://oss.sonatype.org/content/groups/staging/jakarta/
Something is not right here.

**Comment by alexsm82** [comment]
Yes, @m0mus, I thought I had released it correctly, but it looks like that wasn't actually the case.  I'm updating my pom to get it released to staging ASAP but have updated the release tracker in the interim.

**Comment by alexsm82** [comment]
I should be able to close this issue after #21 is merged and I re-run the release job.  That will ensure the correct repo is used and uptake the Jakarta version of JTA.

**Comment by alexsm82** [comment]
Available here: https://oss.sonatype.org/content/groups/staging/jakarta/resource/
