### ISSUE TITLE
Jakarta release has wrong OSGi Bundle-SymbolicName

### ISSUE THREAD

**Issue by rfelcman** [eclipse-ee4j/jca-api#26]
Jakarta release of this API has wrong value of OSGi Bundle-SymbolicName in MANIFEST.MF.
Current value is _javax.resource-api_ but expected value could be _jakarta.resource-api_ .

**Comment by alexsm82** [comment]
Fixed in #27 and #28.  @m0mus does a new release need to be created with the fix?

**Comment by Tomas-Kraus** [comment]
I modified release job and updated artifact in staging. Hope that 1.7.2 (was in pom as snapshot version) is correct.
`[INFO]  * Closing staging repository with ID "jakartaresource-1003"`

This issue can be closed now.

**Comment by alexsm82** [comment]
@Tomas-Kraus the 1.7.2 version was already released: https://mvnrepository.com/artifact/jakarta.resource/jakarta.resource-api/1.7.2

**Comment by Tomas-Kraus** [comment]
OK, so dropping 1.7.2 from staging, we need to update snapshot version to 1.7.3 first.
