### ISSUE TITLE
Public Release

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jca-api#33]
Last CTS runs indicate no failures in this component. It's time to make a public release. Before the release make sure that Eclipse Release Review is passed and all dependencies have been released.

**Comment by alexsm82** [comment]
I have restaged the 1.7.3 release to staging (https://oss.sonatype.org/content/groups/staging/jakarta/resource/jakarta.resource-api/1.7.3/) which now includes the correct JTA dependency version.  I will release the API to maven central this afternoon.

**Comment by alexsm82** [comment]
The 1.7.3 release is now available in Maven Central: http://repo1.maven.org/maven2/jakarta/resource/jakarta.resource-api/1.7.3/.
