### ISSUE TITLE
Update Scope Statement for Jakarta Connector Architecture Project

### ISSUE THREAD

**Issue by ivargrimstad** [eclipse-ee4j/jca-api#36]
Update the scope statement for the project: https://projects.eclipse.org/projects/ee4j.jakartaee-platform/governance

See https://docs.google.com/spreadsheets/d/1FPLjo_DJDOQngVtdrYgaDk98d9NBG-0ODgdmOG3LOsI/edit?usp=sharing for examples.

**Comment by smillidge** [comment]
Current Scope Statement from https://projects.eclipse.org/projects/ee4j.jca is;

`The Jakarta EE Connector Architecture defines a standard architecture for Jakarta EE application components to connect to Enterprise Information Systems.`


Based on Ivar's examples I propose (note naming depends on the name discussion)

`Jakarta Connector Architecture defines a specification document, API and TCK that defines a standard architecture for Jakarta application components to connect to Enterprise Information Systems.`

**Comment by njr-11** [comment]
Sounds good.  One very minor grammar correction is that the second `defines` should be `define` given that the plurality of (specification document, API, TCK) are what define the architecture rather than just the TCK.

**Comment by smillidge** [comment]
Updated the grammar in the scope statement

**Comment by ivargrimstad** [comment]
**Jakarta Connectors defines a standard architecture for Jakarta application components to connect to Enterprise Information Systems.**

**Comment by smillidge** [comment]
@ivargrimstad didn't your suggested example have the "specification document, API and TCK" words in it?

**Comment by waynebeaton** [comment]
I'm going to push forward with this:

> Jakarta Connectors defines a standard architecture for Jakarta application components to connect to Enterprise Information Systems.
