### ISSUE TITLE
Remove deprecated APIs for Jakarta EE 9

### ISSUE THREAD

**Issue by smillidge** [eclipse-ee4j/jca-api#44]
There are some deprecated apis lying around in the api. May as well remove them if we are moving namespace.

**Comment by alexsm82** [comment]
Is this for Jakarta EE 8 or 9?  I thought we weren't supposed to be making changes for Jakarta EE 8.

**Comment by smillidge** [comment]
I meant 9

**Comment by smillidge** [comment]
Deprecated apis were not removed for 9 review again at a later date. I will close this issue
