### ISSUE TITLE
Merge (original) JCA Connectors specification source

### ISSUE THREAD

**Issue by kwsutter** [eclipse-ee4j/jca-api#62]
Just an FYI... The original (oracle) JCA Connectors specification source is now available via this CQ: https://dev.eclipse.org/ipzilla/show_bug.cgi?id=21459

Please import/modify/merge it when time allows, hopefully in time for Jakarta EE 9. Thanks!

**Comment by smillidge** [comment]
Fixed by #63

**Comment by kwsutter** [comment]
Thanks, Steve!  Just want to link this Issue with the overall Jakarta EE 9 Issue #60.
