### ISSUE TITLE
Project naming confusion

### ISSUE THREAD

**Issue by KyleAure** [eclipse-ee4j/jca-api#68]
The Jakarta documentation about this specification indicates that the API uses the naming `jakarta.connectors:jakarta.connectors-api:[version]` (https://jakarta.ee/specifications/connectors/2.0/).  So why are we using a different Artifact/Group IDs here?

https://github.com/eclipse-ee4j/jca-api/blob/b24b3471a445b177b19594e6f296916ab9f026c8/api/pom.xml#L28-L30

**Comment by smillidge** [comment]
That was what it was called before. I will raise at the platform level whether to change these maven coordinates.

**Comment by alexsm82** [comment]
I just checked with Kevin about this.  According to the document for naming rules (which happens to use Jakarta Connectors as an example: https://wiki.eclipse.org/JakartaEE_Maven_Versioning_Rules) it should be `jakarta.resource`, as we've done. The release page (https://jakarta.ee/specifications/connectors/2.0/) had the incorrect coordinates on it when created and will be updated as Jakarta Connectors goes through the approval process.

**Comment by KyleAure** [comment]
Thanks for clearing that up Alex!
