### ISSUE TITLE
Build CI/CD pipeline

### ISSUE THREAD

**Issue by m0mus** [eclipse-ee4j/jca-api#7]
This task is for creating a basic build CI/CD pipeline for this project on Eclipse infrastructure. More information is here: https://ci.eclipse.org/.

**Comment by arjantijms** [comment]
Project CI environment has been requested:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=538669

**Comment by alexsm82** [comment]
The Jenkins CI/CD build pipelines have been created and are green:
https://jenkins.eclipse.org/jca/job/jca-api-EE4J_8/
https://jenkins.eclipse.org/jca/job/jca-api-master/
