### ISSUE TITLE
Need explicit requirement against resource adapter implementing both specs at once

### ISSUE THREAD

**Issue by njr-11** [eclipse-ee4j/jca-api#73]
We should include a requirement in the Jakarta Connectors spec stating that a single resource adapter RAR file must not simultaneously implement both the Jakarta Connectors spec and the Java EE JCA spec.  If any resource adapters choose to implement both at once in a single RAR, I could see this bringing a lot of trouble to application servers as well as users who would end up going through the trouble of having to figure out how to bring in the missing spec classes that aren't provided by the app server, the extra footprint it would require, and the possibility of things not working right.

**Comment by smillidge** [comment]
As there are no backwards compatibility guarantees I don't have a problem stating this. Do you want to make a PR?

**Comment by njr-11** [comment]
Yes, I opened pull #77 to add it and assigned you as the reviewer. Thanks!

**Comment by smillidge** [comment]
Closed by #81
